version: '3.8'
services:
  backend:
    build:
      context: ../DELF-Practice
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - URL_REACT=http://localhost
    ports:
      - 3000:3000

  nginx:
    image: nginx:1.23.3
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ../DELF-Practice-Admin/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
